# Input data
############################
mvals: "data/mvals.csv.gz"
pheno: "data/pheno.csv"

# EWAS model parameters
############################
association_variable: "BMI"
stratified_ewas: "yes" # yes or no
stratify_variables: ["sex"] # If yes, list which variable(s) to stratify on

# Differentially Methylated Region (DMR) Analysis 
#################################################
dmr_analysis: "yes" # yes or no
genome_build: "hg38" # genome build from USCS
min_pvalue: 1e-04 # P-value threshold for beginning a region
window_size: 200 # extend region if another p-value within this distance is found
region_filter: 0.05 # post-filter reported regions

# Parallelization parameters
############################
chunk_size: 5000 # number of methylation sites per chunk 
processing_type: "cluster" # sequential, multisession, multicore, or cluster
workers: 8 # Number of workers per job

# Output parameters
############################
out_directory: "results_logNMR/" # Include trailing '/'
out_type: ".csv.gz" # .csv or .csv.gz
